# Generated by Django 5.2.13 on 2026-04-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
